version: "3.9"
services:
  dating-app:
    container_name: dating-app
    working_dir: /app
    build: .
    hostname: httpd
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file: .env
    environment:
      - DATABASE_HOST=host.docker.internal
    command: sh -c "go run serve/main.go"
    depends_on:
      - db
    volumes:
      - ${PWD}:/app
    ports:
      - "8000:8000"
  db:
    container_name: postgres
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    volumes:
      - "pgdata:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 12345678

volumes:
  pgdata:
