// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// UserPackageHandler is an autogenerated mock type for the UserPackageHandler type
type UserPackageHandler struct {
	mock.Mock
}

// Create provides a mock function with given fields: c
func (_m *UserPackageHandler) Create(c *gin.Context) {
	_m.Called(c)
}

// List provides a mock function with given fields: c
func (_m *UserPackageHandler) List(c *gin.Context) {
	_m.Called(c)
}

// NewUserPackageHandler creates a new instance of UserPackageHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserPackageHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserPackageHandler {
	mock := &UserPackageHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
