// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"

	mock "github.com/stretchr/testify/mock"
)

// UserPairHandler is an autogenerated mock type for the UserPairHandler type
type UserPairHandler struct {
	mock.Mock
}

// Create provides a mock function with given fields: c
func (_m *UserPairHandler) Create(c *gin.Context) {
	_m.Called(c)
}

// NewUserPairHandler creates a new instance of UserPairHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserPairHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserPairHandler {
	mock := &UserPairHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
