// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	context "context"

	service "github.com/hendrihmwn/dating-app-api/app/domain/service"
	mock "github.com/stretchr/testify/mock"
)

// PackageService is an autogenerated mock type for the PackageService type
type PackageService struct {
	mock.Mock
}

// Get provides a mock function with given fields: ctx, params
func (_m *PackageService) Get(ctx context.Context, params service.GetPackageParams) (*service.GetPackageResponse, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *service.GetPackageResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.GetPackageParams) (*service.GetPackageResponse, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.GetPackageParams) *service.GetPackageResponse); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.GetPackageResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.GetPackageParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx
func (_m *PackageService) List(ctx context.Context) (*service.PackageListResponse, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *service.PackageListResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*service.PackageListResponse, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *service.PackageListResponse); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.PackageListResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPackageService creates a new instance of PackageService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPackageService(t interface {
	mock.TestingT
	Cleanup(func())
}) *PackageService {
	mock := &PackageService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
