// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	context "context"

	service "github.com/hendrihmwn/dating-app-api/app/domain/service"
	mock "github.com/stretchr/testify/mock"
)

// UserPackageService is an autogenerated mock type for the UserPackageService type
type UserPackageService struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, params
func (_m *UserPackageService) Create(ctx context.Context, params service.CreateUserPackageParams) (*service.CreateUserPackageResponse, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *service.CreateUserPackageResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.CreateUserPackageParams) (*service.CreateUserPackageResponse, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.CreateUserPackageParams) *service.CreateUserPackageResponse); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.CreateUserPackageResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.CreateUserPackageParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx, params
func (_m *UserPackageService) List(ctx context.Context, params service.ListUserPackageParams) (*service.ListUserPackageResponse, error) {
	ret := _m.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 *service.ListUserPackageResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, service.ListUserPackageParams) (*service.ListUserPackageResponse, error)); ok {
		return rf(ctx, params)
	}
	if rf, ok := ret.Get(0).(func(context.Context, service.ListUserPackageParams) *service.ListUserPackageResponse); ok {
		r0 = rf(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.ListUserPackageResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, service.ListUserPackageParams) error); ok {
		r1 = rf(ctx, params)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUserPackageService creates a new instance of UserPackageService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserPackageService(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserPackageService {
	mock := &UserPackageService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
